In [1]:
import pandas as pd
import numpy as np

In [2]:
from _counties import get_counties_df
counties_df = get_counties_df()
counties_df

    CO_FIPS     CO_NAME
0         5       CACHE
1        13    DUCHESNE
2        11       DAVIS
3        27     MILLARD
4        51     WASATCH
5         3   BOX ELDER
6        57       WEBER
7        23        JUAB
8        39     SANPETE
9        53  WASHINGTON
10       19       GRAND
11       33        RICH
12        7      CARBON
13        9     DAGGETT
14        1      BEAVER
15       41      SEVIER
16       17    GARFIELD
17       45      TOOELE
18       43      SUMMIT
19       31       PIUTE
20       47      UINTAH
21       21        IRON
22       15       EMERY
23       55       WAYNE
24       37    SAN JUAN
25       29      MORGAN
26       25        KANE
27       35   SALT LAKE
28       49        UTAH

In [3]:
# read excel file into df
file_path = r"data\GPI-Base-Data-20251201\2023_2024_UDEM_calibration_data_20251201.xlsx"

# Read **first** sheet (sheet_name=0)
base_year_2023_df = pd.read_excel(file_path, sheet_name=0, usecols=['Year','Geography','POP','HH','GQ','HHPOP']).rename(columns={'Year':'YEAR'})

base_year_2023_df['CO_NAME'] = base_year_2023_df['Geography'].str.replace(' COUNTY', '')
base_year_2023_df['CO_NAME'] = base_year_2023_df['CO_NAME'].str.upper()

base_year_2023_df.drop(columns=['Geography'], inplace=True)

base_year_2023_df = base_year_2023_df.merge(counties_df, on='CO_NAME')

#base_year_2023_df['YEAR'] = 2023

display(base_year_2023_df)

,YEAR,POP,HH,GQ,HHPOP,CO_NAME,CO_FIPS
0,2023,7.313585e+03,2381.171904,299.428835,7.014156e+03,BEAVER,1
1,2023,6.125078e+04,20602.544283,166.019149,6.108476e+04,BOX ELDER,3
2,2023,1.416997e+05,45994.953039,4463.412384,1.372363e+05,CACHE,5
3,2023,2.065354e+04,7948.667611,116.045823,2.053749e+04,CARBON,7
4,2023,9.977325e+02,420.750519,0.000000,9.977325e+02,DAGGETT,9
5,2023,3.773785e+05,122330.094345,2404.727933,3.749737e+05,DAVIS,11
6,2023,2.011194e+04,6777.016795,87.471292,2.002446e+04,DUCHESNE,13
7,2023,1.003529e+04,3794.104779,58.000000,9.977291e+03,EMERY,15
8,2023,5.140647e+03,1963.103222,204.163255,4.936484e+03,GARFIELD,17
9,2023,9.842434e+03,4170.780935,156.000000,9.686434e+03,GRAND,19
10,2023,6.604447e+04,22269.788753,1700.168929,6.434430e+04,IRON,21
11,2023,1.276626e+04,4093.416063,101.000000,1.266526e+04,JUAB,23
12,2023,8.387495e+03,3208.666009,169.867531,8.217628e+03,KANE,25
13,2023,1.348447e+04,4476.475549,47.236279,1.343723e+04,MILLARD,27
14,2023,1.305949e+04,4333.634643,0.000000,1.305949e+04,MORGAN,29
15,2023,1.564595e+03,611.296939,0.000000,1.564595e+03,PIUTE,31
16,2023,2.724551e+03,985.855430,54.000000,2.670551e+03,RICH,33
17,2023,1.220554e+06,437303.558546,18584.065688,1.201970e+06,SALT LAKE,35
18,2023,1.495360e+04,5396.386739,408.704187,1.454490e+04,SAN JUAN,37
19,2023,3.034690e+04,9246.497321,2818.575779,2.752832e+04,SANPETE,39
20,2023,2.216400e+04,7598.817883,282.950139,2.188105e+04,SEVIER,41
21,2023,4.349093e+04,15294.907850,129.000000,4.336193e+04,SUMMIT,43
22,2023,7.940766e+04,25795.204484,298.936890,7.910872e+04,TOOELE,45
23,2023,3.652700e+04,12505.093137,115.000000,3.641200e+04,UINTAH,47
24,2023,7.277517e+05,220334.815530,16935.334375,7.108164e+05,UTAH,49
25,2023,3.793283e+04,13205.783005,211.947049,3.772088e+04,WASATCH,51
26,2023,1.985282e+05,73168.316952,3064.564821,1.954636e+05,WASHINGTON,53
27,2023,2.522742e+03,955.567125,0.000000,2.522742e+03,WAYNE,55
28,2023,2.698107e+05,97325.259903,3767.440336,2.660433e+05,WEBER,57
29,2024,7.338583e+03,2410.611574,291.063107,7.047519e+03,BEAVER,1
30,2024,6.175474e+04,20927.388174,166.710626,6.158803e+04,BOX ELDER,3
31,2024,1.434826e+05,46967.300114,4532.306018,1.389503e+05,CACHE,5
32,2024,2.044151e+04,7897.067499,117.261878,2.032424e+04,CARBON,7
33,2024,9.837361e+02,419.138146,0.000000,9.837361e+02,DAGGETT,9
34,2024,3.785723e+05,124068.270565,2446.950075,3.761253e+05,DAVIS,11
35,2024,2.017093e+04,6843.256781,88.281508,2.008265e+04,DUCHESNE,13
36,2024,9.913302e+03,3779.538578,58.000000,9.855302e+03,EMERY,15
37,2024,5.114644e+03,1956.346136,203.983874,4.910661e+03,GARFIELD,17
38,2024,9.898431e+03,4231.251442,156.000000,9.742431e+03,GRAND,19
39,2024,6.789743e+04,23055.952944,1735.183006,6.616225e+04,IRON,21
40,2024,1.311625e+04,4227.251146,101.000000,1.301525e+04,JUAB,23
41,2024,8.364490e+03,3212.237614,168.960910,8.195529e+03,KANE,25
42,2024,1.360946e+04,4542.216687,48.372061,1.356109e+04,MILLARD,27
43,2024,1.309348e+04,4414.255453,0.000000,1.309348e+04,MORGAN,29
44,2024,1.648594e+03,642.595680,0.000000,1.648594e+03,PIUTE,31
45,2024,2.804550e+03,1022.116896,54.000000,2.750550e+03,RICH,33
46,2024,1.232666e+06,445859.100232,18796.827440,1.213869e+06,SALT LAKE,35
47,2024,1.500459e+04,5486.490395,409.644500,1.459495e+04,SAN JUAN,37
48,2024,3.089988e+04,9408.205877,2861.940355,2.803794e+04,SANPETE,39
49,2024,2.197199e+04,7583.269747,278.733770,2.169326e+04,SEVIER,41
50,2024,4.330391e+04,15422.908500,129.000000,4.317491e+04,SUMMIT,43
51,2024,8.185561e+04,26788.144236,304.500859,8.155111e+04,TOOELE,45
52,2024,3.621498e+04,12531.545889,115.000000,3.609998e+04,UINTAH,47
53,2024,7.496043e+05,228987.660327,17283.763397,7.323205e+05,UTAH,49
54,2024,3.880180e+04,13642.623765,226.274314,3.857553e+04,WASATCH,51
55,2024,2.043861e+05,75803.068328,3146.982125,2.012391e+05,WASHINGTON,53
56,2024,2.542740e+03,960.273210,0.000000,2.542740e+03,WAYNE,55
57,2024,2.713815e+05,98675.905807,3808.280014,2.675733e+05,WEBER,57

In [4]:
gpi_year_age_df = pd.read_csv("data/GPI-SE-Data-20251121/utah_proj_v2025_sya_2020_2065.csv").rename(columns={'Year':'YEAR'})
gpi_2025_age_df = gpi_year_age_df[gpi_year_age_df['YEAR'].isin([2023,2024])]
gpi_2025_age_df

            Geography  YEAR  Age  Pop
303     Beaver County  2023    0  103
304     Beaver County  2023    1  114
305     Beaver County  2023    2   95
306     Beaver County  2023    3  110
307     Beaver County  2023    4  110
...               ...   ...  ...  ...
135234  State of Utah  2024   96  846
135235  State of Utah  2024   97  580
135236  State of Utah  2024   98  401
135237  State of Utah  2024   99  251
135238  State of Utah  2024  100  346

[6060 rows x 4 columns]

In [5]:
# df columns expected:
# Geography | Year | Age | Pop

# 1. Define your age-group bins
bins = [0, 17, 64, 200]          # max age large enough to include all ages
labels = ["POP_00_17_pct", "POP_18_64_pct", "POP_65P_pct"]

# 2. Assign each record to an age group
gpi_2025_age_df["AgeGroup"] = pd.cut(gpi_2025_age_df["Age"].astype(int), bins=bins, labels=labels, right=True)

# 3. Aggregate
gpi_2025_age_groups_df = (
    gpi_2025_age_df.groupby(["Geography", "YEAR", "AgeGroup"], as_index=False, observed=False)
      .agg({"Pop": "sum"})
      .rename(columns={"AgeGroup": "Age"})
)

gpi_2025_age_groups_df = gpi_2025_age_groups_df[gpi_2025_age_groups_df['Geography'].str.contains(' County')]

gpi_2025_age_groups_df['CO_NAME'] = gpi_2025_age_groups_df['Geography'].str.replace(' County','').str.upper()

gpi_2025_age_groups_df.drop(columns=['Geography'], inplace=True)

display(gpi_2025_age_groups_df)

C:\Users\bhereth\AppData\Local\Temp\ipykernel_28568\3606837317.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gpi_2025_age_df["AgeGroup"] = pd.cut(gpi_2025_age_df["Age"].astype(int), bins=bins, labels=labels, right=True)

     YEAR            Age     Pop CO_NAME
0    2023  POP_00_17_pct    1992  BEAVER
1    2023  POP_18_64_pct    4129  BEAVER
2    2023    POP_65P_pct    1095  BEAVER
3    2024  POP_00_17_pct    1969  BEAVER
4    2024  POP_18_64_pct    4151  BEAVER
..    ...            ...     ...     ...
175  2023  POP_18_64_pct  165068   WEBER
176  2023    POP_65P_pct   34713   WEBER
177  2024  POP_00_17_pct   65593   WEBER
178  2024  POP_18_64_pct  166459   WEBER
179  2024    POP_65P_pct   35940   WEBER

[174 rows x 4 columns]

In [6]:
# get percent of total in each Age Category
# 1. Compute total population by CO_NAME + Year
totals = (
    gpi_2025_age_groups_df
        .groupby(["CO_NAME", "YEAR"], as_index=False)
        .agg(TotalPop=("Pop", "sum"))
)

# 2. Merge totals back to the age-group DataFrame
gpi_2025_age_dist_df = gpi_2025_age_groups_df.merge(totals, on=["CO_NAME", "YEAR"])

# 3. Compute percent of total
gpi_2025_age_dist_df["PctOfTotal"] = gpi_2025_age_dist_df["Pop"] / gpi_2025_age_dist_df["TotalPop"]

gpi_2025_age_dist_df = (
    gpi_2025_age_dist_df[["CO_NAME", "YEAR", "Age", "PctOfTotal"]]
        .pivot(index=["CO_NAME",'YEAR'], columns="Age", values="PctOfTotal")
        .reset_index()
)

gpi_2025_age_dist_df

Age     CO_NAME  YEAR  POP_00_17_pct  POP_18_64_pct  POP_65P_pct
0        BEAVER  2023       0.276053       0.572201     0.151746
1        BEAVER  2024       0.272112       0.573659     0.154229
2     BOX ELDER  2023       0.287059       0.576945     0.135996
3     BOX ELDER  2024       0.280810       0.579138     0.140052
4         CACHE  2023       0.267763       0.628493     0.103743
5         CACHE  2024       0.259574       0.635060     0.105366
6        CARBON  2023       0.243869       0.562681     0.193450
7        CARBON  2024       0.239573       0.563303     0.197124
8       DAGGETT  2023       0.204431       0.534743     0.260826
9       DAGGETT  2024       0.192464       0.537678     0.269857
10        DAVIS  2023       0.284348       0.600712     0.114940
11        DAVIS  2024       0.276527       0.604489     0.118985
12     DUCHESNE  2023       0.304764       0.560272     0.134963
13     DUCHESNE  2024       0.298634       0.563071     0.138295
14        EMERY  2023       0.260127       0.551773     0.188100
15        EMERY  2024       0.253571       0.551122     0.195306
16     GARFIELD  2023       0.210547       0.538961     0.250492
17     GARFIELD  2024       0.206917       0.538933     0.254150
18        GRAND  2023       0.197088       0.583983     0.218929
19        GRAND  2024       0.194425       0.579713     0.225862
20         IRON  2023       0.257087       0.610602     0.132311
21         IRON  2024       0.250758       0.614001     0.135242
22         JUAB  2023       0.314738       0.566370     0.118892
23         JUAB  2024       0.308152       0.572326     0.119522
24         KANE  2023       0.225445       0.534906     0.239649
25         KANE  2024       0.219701       0.534404     0.245896
26      MILLARD  2023       0.288184       0.527811     0.184005
27      MILLARD  2024       0.282468       0.529394     0.188138
28       MORGAN  2023       0.305373       0.564360     0.130267
29       MORGAN  2024       0.290969       0.573301     0.135729
30        PIUTE  2023       0.198065       0.514194     0.287742
31        PIUTE  2024       0.197062       0.525092     0.277846
32         RICH  2023       0.263119       0.526610     0.210272
33         RICH  2024       0.260776       0.531609     0.207615
34    SALT LAKE  2023       0.235677       0.639705     0.124618
35    SALT LAKE  2024       0.229768       0.641997     0.128235
36     SAN JUAN  2023       0.261066       0.585659     0.153274
37     SAN JUAN  2024       0.253369       0.586995     0.159636
38      SANPETE  2023       0.230615       0.622323     0.147062
39      SANPETE  2024       0.227255       0.624500     0.148245
40       SEVIER  2023       0.262441       0.562354     0.175204
41       SEVIER  2024       0.255547       0.563679     0.180774
42       SUMMIT  2023       0.205915       0.622733     0.171352
43       SUMMIT  2024       0.197976       0.618646     0.183378
44       TOOELE  2023       0.290536       0.611235     0.098229
45       TOOELE  2024       0.284610       0.616060     0.099330
46       UINTAH  2023       0.294057       0.578663     0.127280
47       UINTAH  2024       0.283915       0.583417     0.132667
48         UTAH  2023       0.295278       0.624404     0.080318
49         UTAH  2024       0.288797       0.630049     0.081154
50      WASATCH  2023       0.270701       0.586613     0.142686
51      WASATCH  2024       0.261182       0.589876     0.148942
52   WASHINGTON  2023       0.228163       0.547306     0.224532
53   WASHINGTON  2024       0.222995       0.550307     0.226698
54        WAYNE  2023       0.219904       0.535714     0.244382
55        WAYNE  2024       0.221691       0.533493     0.244817
56        WEBER  2023       0.250046       0.619646     0.130308
57        WEBER  2024       0.244757       0.621134     0.134108

# Apply 2025 split to 2023

In [7]:
pop_df = pd.merge(base_year_2023_df, gpi_2025_age_dist_df, on=('CO_NAME','YEAR'))

pop_df['TOTPOP'] = np.round(pop_df['POP']).astype(int)
pop_df['HHPOP'] = np.round(pop_df['HHPOP']).astype(int)
pop_df['GQPOP'] = pop_df['TOTPOP'] - pop_df['HHPOP']

pop_df['POP0017'] = np.round(pop_df['POP'] * pop_df['POP_00_17_pct']).astype(int)
pop_df['POP1864'] = np.round(pop_df['POP'] * pop_df['POP_18_64_pct']).astype(int)
pop_df['POP65P'] = pop_df['TOTPOP'] - pop_df['POP0017'] - pop_df['POP1864']

pop_df = pop_df[['CO_FIPS','YEAR','TOTPOP','GQPOP','HHPOP','POP0017','POP1864','POP65P','HH','CO_NAME']]

pop_melt_df = pop_df.melt(id_vars=['CO_FIPS','YEAR','CO_NAME'], var_name='TDM_VARIABLE', value_name='VALUE')
pop_melt_df['VALUE'] = pop_melt_df['VALUE'].astype(int)
pop_melt_df

     CO_FIPS  YEAR     CO_NAME TDM_VARIABLE   VALUE
0          1  2023      BEAVER       TOTPOP    7314
1          3  2023   BOX ELDER       TOTPOP   61251
2          5  2023       CACHE       TOTPOP  141700
3          7  2023      CARBON       TOTPOP   20654
4          9  2023     DAGGETT       TOTPOP     998
..       ...   ...         ...          ...     ...
401       49  2024        UTAH           HH  228987
402       51  2024     WASATCH           HH   13642
403       53  2024  WASHINGTON           HH   75803
404       55  2024       WAYNE           HH     960
405       57  2024       WEBER           HH   98675

[406 rows x 5 columns]

In [8]:
pop_melt_df[['CO_FIPS','YEAR','TDM_VARIABLE','VALUE','CO_NAME']].to_csv('intermediate/tdm_population_by_county_2023_2024.csv', index=False)