In [1]:
import pandas as pd
import numpy as np

In [2]:
# taken from last version
counties_more_df = pd.DataFrame([
[   1,"Beaver"              ,"Rural","0 - UDOT (Rural)"  ],
[   3,"Box Elder"           ,"Rural","0 - UDOT (Rural)"  ],
[   5,"Cache"               ,"Urban","2 - Cache"         ],
[   7,"Carbon"              ,"Rural","0 - UDOT (Rural)"  ],
[   9,"Daggett"             ,"Rural","0 - UDOT (Rural)"  ],
[  11,"Davis"               ,"Urban","1 - Wasatch Front" ],
[  13,"Duchesne"            ,"Rural","0 - UDOT (Rural)"  ],
[  15,"Emery"               ,"Rural","0 - UDOT (Rural)"  ],
[  17,"Garfield"            ,"Rural","0 - UDOT (Rural)"  ],
[  19,"Grand"               ,"Rural","0 - UDOT (Rural)"  ],
[  21,"Iron"                ,"Rural","5 - Iron"          ],
[  23,"Juab"                ,"Rural","0 - UDOT (Rural)"  ],
[  25,"Kane"                ,"Rural","0 - UDOT (Rural)"  ],
[  27,"Millard"             ,"Rural","0 - UDOT (Rural)"  ],
[  29,"Morgan"              ,"Rural","0 - UDOT (Rural)"  ],
[  31,"Piute"               ,"Rural","0 - UDOT (Rural)"  ],
[  33,"Rich"                ,"Rural","0 - UDOT (Rural)"  ],
[  35,"Salt Lake"           ,"Urban","1 - Wasatch Front" ],
[  37,"San Juan"            ,"Rural","0 - UDOT (Rural)"  ],
[  39,"Sanpete"             ,"Rural","0 - UDOT (Rural)"  ],
[  41,"Sevier"              ,"Rural","0 - UDOT (Rural)"  ],
[  43,"Summit"              ,"Rural","4 - Summit-Wasatch"],
[  45,"Tooele"              ,"Rural","0 - UDOT (Rural)"  ],
[  47,"Uintah"              ,"Rural","0 - UDOT (Rural)"  ],
[  49,"Utah"                ,"Urban","1 - Wasatch Front" ],
[  51,"Wasatch"             ,"Rural","4 - Summit-Wasatch"],
[  53,"Washington"          ,"Urban","3 - Dixie"         ],
[  55,"Wayne"               ,"Rural","0 - UDOT (Rural)"  ],
[  57,"Weber"               ,"Urban","1 - Wasatch Front" ],
[1049,"State of Utah"       ,"State","6 - State"         ],
[9003,"Box Elder - Rural"   ,"Rural","0 - UDOT (Rural)"  ],
[9103,"Box Elder - WFRC"    ,"Urban","1 - Wasatch Front" ],
[9057,"Weber - Ogden Valley","Rural","0 - UDOT (Rural)"  ],
[9157,"Weber - WFRC"        ,"Urban","1 - Wasatch Front" ]
],columns=["CO_FIPS","CO_NAME","Urban_Rural","Subarea"])

counties_more_df['CO_NAME'] = counties_more_df["CO_NAME"].str.upper()

counties_more_df

    CO_FIPS               CO_NAME Urban_Rural             Subarea
0         1                BEAVER       Rural    0 - UDOT (Rural)
1         3             BOX ELDER       Rural    0 - UDOT (Rural)
2         5                 CACHE       Urban           2 - Cache
3         7                CARBON       Rural    0 - UDOT (Rural)
4         9               DAGGETT       Rural    0 - UDOT (Rural)
5        11                 DAVIS       Urban   1 - Wasatch Front
6        13              DUCHESNE       Rural    0 - UDOT (Rural)
7        15                 EMERY       Rural    0 - UDOT (Rural)
8        17              GARFIELD       Rural    0 - UDOT (Rural)
9        19                 GRAND       Rural    0 - UDOT (Rural)
10       21                  IRON       Rural            5 - Iron
11       23                  JUAB       Rural    0 - UDOT (Rural)
12       25                  KANE       Rural    0 - UDOT (Rural)
13       27               MILLARD       Rural    0 - UDOT (Rural)
14       29                MORGAN       Rural    0 - UDOT (Rural)
15       31                 PIUTE       Rural    0 - UDOT (Rural)
16       33                  RICH       Rural    0 - UDOT (Rural)
17       35             SALT LAKE       Urban   1 - Wasatch Front
18       37              SAN JUAN       Rural    0 - UDOT (Rural)
19       39               SANPETE       Rural    0 - UDOT (Rural)
20       41                SEVIER       Rural    0 - UDOT (Rural)
21       43                SUMMIT       Rural  4 - Summit-Wasatch
22       45                TOOELE       Rural    0 - UDOT (Rural)
23       47                UINTAH       Rural    0 - UDOT (Rural)
24       49                  UTAH       Urban   1 - Wasatch Front
25       51               WASATCH       Rural  4 - Summit-Wasatch
26       53            WASHINGTON       Urban           3 - Dixie
27       55                 WAYNE       Rural    0 - UDOT (Rural)
28       57                 WEBER       Urban   1 - Wasatch Front
29     1049         STATE OF UTAH       State           6 - State
30     9003     BOX ELDER - RURAL       Rural    0 - UDOT (Rural)
31     9103      BOX ELDER - WFRC       Urban   1 - Wasatch Front
32     9057  WEBER - OGDEN VALLEY       Rural    0 - UDOT (Rural)
33     9157          WEBER - WFRC       Urban   1 - Wasatch Front

In [3]:
se_df = pd.concat([pd.read_csv('intermediate/split_emp.csv'), pd.read_csv('intermediate/split_pop.csv')])
se_df

      CO_FIPS  YEAR VARIABLE   VALUE
0           1  2023     AGRI     730
1           1  2023     CONS     264
2           1  2023     FOOD     511
3           1  2023     GVED     750
4           1  2023      HBJ     244
...       ...   ...      ...     ...
9697     9157  2065    HHPOP  367411
9698     9157  2065  POP0017   59084
9699     9157  2065  POP1864  222289
9700     9157  2065   POP65P   91658
9701     9157  2065   TOTPOP  373033

[10098 rows x 4 columns]

In [4]:
se_df[(se_df['YEAR']==2023) & (se_df['VARIABLE']=='HH')]

      CO_FIPS  YEAR VARIABLE   VALUE
1           1  2023       HH    2280
295         3  2023       HH   20024
589         5  2023       HH   44622
883         7  2023       HH    7861
1177        9  2023       HH     405
1471       11  2023       HH  120087
1765       13  2023       HH    6560
2059       15  2023       HH    3756
2353       17  2023       HH    1877
2647       19  2023       HH    3984
2941       21  2023       HH   21467
3235       23  2023       HH    3975
3529       25  2023       HH    3104
3823       27  2023       HH    4370
4117       29  2023       HH    4211
4411       31  2023       HH     605
4705       33  2023       HH     958
4999       35  2023       HH  428373
5293       37  2023       HH    5167
5587       39  2023       HH    9226
5881       41  2023       HH    7586
6175       43  2023       HH   14382
6469       45  2023       HH   24833
6763       47  2023       HH   12148
7057       49  2023       HH  211379
7351       51  2023       HH   12556
7645       53  2023       HH   70844
7939       55  2023       HH     947
8233       57  2023       HH   94481
8527     9003  2023       HH    9191
8821     9057  2023       HH    3212
9115     9103  2023       HH   10833
9409     9157  2023       HH   91269

In [5]:
se_pivot_df = se_df.pivot(index=['CO_FIPS','YEAR'],columns='VARIABLE',values='VALUE').reset_index().fillna(0).astype(int)
se_pivot_df

VARIABLE,CO_FIPS,YEAR,AGRI,CONS,FOOD,GQPOP,GVED,HBJ,HH,HHPOP,...,MANU,MING,OFFI,OTHR,POP0017,POP1864,POP65P,RETL,TOTPOP,WSLE
0,1,2023,730,264,511,299,750,244,2280,7015,...,194,101,129,906,1942,4239,1133,485,7314,266
1,1,2025,0,0,0,369,0,0,2472,7163,...,0,0,0,0,2071,4310,1152,0,7533,0
2,1,2026,0,0,0,351,0,0,2516,7226,...,0,0,0,0,2030,4353,1194,0,7577,0
3,1,2027,0,0,0,295,0,0,2561,7287,...,0,0,0,0,1996,4363,1223,0,7582,0
4,1,2028,0,0,0,303,0,0,2600,7331,...,0,0,0,0,1971,4386,1277,0,7634,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1381,9157,2061,0,0,0,5406,0,0,157287,356144,...,0,0,0,0,59730,216417,85404,0,361551,0
1382,9157,2062,0,0,0,5460,0,0,159127,358961,...,0,0,0,0,59495,217801,87125,0,364421,0
1383,9157,2063,0,0,0,5513,0,0,160960,361776,...,0,0,0,0,59303,219248,88737,0,367288,0
1384,9157,2064,0,0,0,5567,0,0,162781,364591,...,0,0,0,0,59165,220852,90141,0,370158,0
1385,9157,2065,0,0,0,5622,0,0,164591,367411,...,0,0,0,0,59084,222289,91658,0,373033,0

In [6]:
# identify numeric columns except keys
value_cols = [c for c in se_pivot_df.columns if c not in ["CO_FIPS", "YEAR"]]

# --- filter only CO_FIPS < 100 before summing --- to avoid split records
se_utah_counties_df = se_pivot_df[se_pivot_df["CO_FIPS"] < 100].copy()

# compute statewide totals by YEAR using only CO_FIPS < 100
utah_totals_df = (
    se_utah_counties_df
        .groupby("YEAR")[value_cols]
        .sum()
        .reset_index()
)

# assign the statewide FIPS
utah_totals_df["CO_FIPS"] = 1049

# reorder columns
utah_totals_df = utah_totals_df[["CO_FIPS", "YEAR"] + value_cols]

In [7]:
se_final_df = pd.concat([se_pivot_df,utah_totals_df]).copy()

se_final_df[';INDEX'] = se_final_df['CO_FIPS'].astype(str) + se_final_df['YEAR'].astype(str)
se_final_df[';INDEX'] = se_final_df[';INDEX'].astype(int)

se_final_df['HHSIZE'] = se_final_df['HHPOP'] / se_final_df['HH']
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].replace([np.inf, -np.inf], 0)
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].fillna(0).round(2)

se_final_df['ALLEMP'] = se_final_df['FOOD'] + se_final_df['MANU'] + se_final_df['WSLE'] + se_final_df['OFFI'] + se_final_df['GVED'] + se_final_df['HLTH'] + se_final_df['OTHR'] + se_final_df['AGRI'] + se_final_df['MING'] + se_final_df['CONS'] + se_final_df['HBJ']

se_final_df = se_final_df[[';INDEX','CO_FIPS','YEAR','TOTPOP','GQPOP','HHPOP','HH','HHSIZE','POP0017','POP1864','POP65P','ALLEMP','RETL','FOOD','MANU','WSLE','OFFI','GVED','HLTH','OTHR','AGRI','MING','CONS','HBJ']]

# add extra columns
se_final_df['Job_HH'] = np.round(se_final_df['ALLEMP'] / se_final_df['HH'],2)
se_final_df['WrkPop_Job'] = np.round(se_final_df['POP1864'] / se_final_df['ALLEMP'],2)

se_final_df = se_final_df.merge(counties_more_df, on='CO_FIPS').sort_values([';INDEX'])

se_final_df

,;INDEX,CO_FIPS,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea
0,12023,1,2023,7314,299,7015,2280,3.08,1942,4239,...,906,730,101,264,244,1.86,1.0,BEAVER,Rural,0 - UDOT (Rural)
1,12025,1,2025,7533,369,7163,2472,2.90,2071,4310,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
2,12026,1,2026,7577,351,7226,2516,2.87,2030,4353,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
3,12027,1,2027,7582,295,7287,2561,2.85,1996,4363,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
4,12028,1,2028,7634,303,7331,2600,2.82,1971,4386,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1381,91572061,9157,2061,361551,5406,356144,157287,2.26,59730,216417,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1382,91572062,9157,2062,364421,5460,358961,159127,2.26,59495,217801,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1383,91572063,9157,2063,367288,5513,361776,160960,2.25,59303,219248,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1384,91572064,9157,2064,370158,5567,364591,162781,2.24,59165,220852,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1385,91572065,9157,2065,373033,5622,367411,164591,2.23,59084,222289,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front

# Export final table

In [8]:
# Final columns
# ;Index,CO_FIPS,YEAR,TOTPOP,GQ_Pop,HH_Pop,HH,HH_Size,POP_00_17,POP_18_64,POP_65P,ALLEMP,RETL,FOOD,MANU,WSLE,OFFI,GVED,HLTH,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea

# EXPORT ONLY 2023 - FOR NOW
se_final_df[se_final_df['YEAR']==2023].to_csv('results/ControlTotal_SE_AllCounties.csv', index=False)
se_final_df[se_final_df['YEAR']==2023]

,;INDEX,CO_FIPS,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea
0,12023,1,2023,7314,299,7015,2280,3.08,1942,4239,...,906,730,101,264,244,1.86,1.00,BEAVER,Rural,0 - UDOT (Rural)
42,32023,3,2023,61251,166,61085,20024,3.05,16811,35603,...,5740,1579,82,2678,1336,1.57,1.14,BOX ELDER,Rural,0 - UDOT (Rural)
84,52023,5,2023,141700,4467,137233,44622,3.08,35465,90994,...,19766,1829,153,4485,2518,1.85,1.10,CACHE,Urban,2 - Cache
126,72023,7,2023,20654,116,20538,7861,2.61,4829,11702,...,2458,426,632,513,155,1.34,1.11,CARBON,Rural,0 - UDOT (Rural)
168,92023,9,2023,998,0,998,405,2.46,181,532,...,98,67,2,13,13,1.43,0.92,DAGGETT,Rural,0 - UDOT (Rural)
210,112023,11,2023,377378,2429,374949,120087,3.12,101351,229841,...,57704,853,328,14921,5888,1.66,1.15,DAVIS,Urban,1 - Wasatch Front
252,132023,13,2023,20112,87,20025,6560,3.05,5844,11414,...,2117,1271,1878,676,451,1.82,0.96,DUCHESNE,Rural,0 - UDOT (Rural)
294,152023,15,2023,10035,58,9977,3756,2.66,2407,5675,...,982,587,407,695,99,1.32,1.14,EMERY,Rural,0 - UDOT (Rural)
336,172023,17,2023,5141,204,4937,1877,2.63,1043,2746,...,513,285,13,161,121,1.80,0.81,GARFIELD,Rural,0 - UDOT (Rural)
378,192023,19,2023,9842,156,9686,3984,2.43,1868,5675,...,1931,101,114,449,535,2.13,0.67,GRAND,Rural,0 - UDOT (Rural)
420,212023,21,2023,66044,1693,64351,21467,3.00,16118,40753,...,8196,1157,345,3116,924,1.51,1.26,IRON,Rural,5 - Iron
462,232023,23,2023,12766,101,12665,3975,3.19,3871,7348,...,928,422,85,564,312,1.46,1.27,JUAB,Rural,0 - UDOT (Rural)
504,252023,25,2023,8387,168,8219,3104,2.65,1806,4473,...,2142,169,40,299,78,1.82,0.79,KANE,Rural,0 - UDOT (Rural)
546,272023,27,2023,13484,185,13299,4370,3.04,3728,7179,...,1556,1247,132,450,298,1.63,1.01,MILLARD,Rural,0 - UDOT (Rural)
588,292023,29,2023,13059,0,13059,4211,3.10,3612,7604,...,1989,447,78,796,245,1.36,1.33,MORGAN,Rural,0 - UDOT (Rural)
630,312023,31,2023,1565,0,1565,605,2.59,303,823,...,118,153,24,17,47,1.09,1.24,PIUTE,Rural,0 - UDOT (Rural)
672,332023,33,2023,2725,54,2671,958,2.79,686,1462,...,592,146,27,134,212,1.90,0.80,RICH,Rural,0 - UDOT (Rural)
714,352023,35,2023,1220554,18582,1201972,428373,2.81,272699,786677,...,273975,1249,4485,65638,29337,2.26,0.81,SALT LAKE,Urban,1 - Wasatch Front
756,372023,37,2023,14954,409,14545,5167,2.81,3655,8805,...,1101,782,358,310,341,1.30,1.31,SAN JUAN,Rural,0 - UDOT (Rural)
798,392023,39,2023,30347,2808,27539,9226,2.98,6792,19005,...,2659,1260,123,1080,574,1.50,1.38,SANPETE,Rural,0 - UDOT (Rural)
840,412023,41,2023,22164,281,21883,7586,2.88,5560,12483,...,2150,937,679,725,460,1.58,1.04,SEVIER,Rural,0 - UDOT (Rural)
882,432023,43,2023,43491,129,43362,14382,3.02,8314,26756,...,18058,883,87,3235,2534,3.17,0.59,SUMMIT,Rural,4 - Summit-Wasatch
924,452023,45,2023,79408,298,79110,24833,3.19,22072,49262,...,6398,557,260,1834,568,1.03,1.92,TOOELE,Rural,0 - UDOT (Rural)
966,472023,47,2023,36527,115,36412,12148,3.00,10050,21521,...,3805,1316,2199,1731,524,1.54,1.15,UINTAH,Rural,0 - UDOT (Rural)
1008,492023,49,2023,727752,16935,710817,211379,3.36,205109,462766,...,110231,3739,857,36369,13494,1.91,1.15,UTAH,Urban,1 - Wasatch Front
1050,512023,51,2023,37933,216,37717,12556,3.00,9560,22420,...,7624,465,78,2506,1474,1.72,1.04,WASATCH,Rural,4 - Summit-Wasatch
1092,532023,53,2023,198528,3086,195442,70844,2.76,42893,109262,...,34668,710,673,12142,4858,1.62,0.95,WASHINGTON,Urban,3 - Dixie
1134,552023,55,2023,2523,0,2523,947,2.66,559,1330,...,463,181,25,259,190,2.15,0.65,WAYNE,Rural,0 - UDOT (Rural)
1176,572023,57,2023,269811,3773,266038,94481,2.82,64538,168059,...,38156,1570,205,10740,3911,1.56,1.14,WEBER,Urban,1 - Wasatch Front
1386,10492023,1049,2023,3456447,56815,3399632,1142068,2.98,853666,2156409,...,607024,25118,14470,166800,71741,1.92,0.98,STATE OF UTAH,State,6 - State
1218,90032023,9003,2023,28788,78,28710,9191,3.12,7901,16733,...,1642,731,51,1259,514,1.49,1.22,BOX ELDER - RURAL,Rural,0 - UDOT (Rural)
1260,90572023,9057,2023,8634,121,8513,3212,2.65,2065,5378,...,992,28,1,344,85,0.96,1.74,WEBER - OGDEN VALLEY,Rural,0 - UDOT (Rural)
1302,91032023,9103,2023,32463,88,32375,10833,2.99,8910,18870,...,4098,848,31,1419,822,1.63,1.07,BOX ELDER - WFRC,Urban,1 - Wasatch Front
1344,91572023,9157,2023,261177,3652,257525,91269,2.82,62473,162681,...,37164,1542,204,10396,3826,1.58,1.13,WEBER - WFRC,Urban,1 - Wasatch Front