In [1]:
import pandas as pd
import numpy as np

In [2]:
# taken from last version
counties_more_df = pd.DataFrame([
[   1,"Beaver"              ,"Rural","0 - UDOT (Rural)"  ],
[   3,"Box Elder"           ,"Rural","0 - UDOT (Rural)"  ],
[   5,"Cache"               ,"Urban","2 - Cache"         ],
[   7,"Carbon"              ,"Rural","0 - UDOT (Rural)"  ],
[   9,"Daggett"             ,"Rural","0 - UDOT (Rural)"  ],
[  11,"Davis"               ,"Urban","1 - Wasatch Front" ],
[  13,"Duchesne"            ,"Rural","0 - UDOT (Rural)"  ],
[  15,"Emery"               ,"Rural","0 - UDOT (Rural)"  ],
[  17,"Garfield"            ,"Rural","0 - UDOT (Rural)"  ],
[  19,"Grand"               ,"Rural","0 - UDOT (Rural)"  ],
[  21,"Iron"                ,"Rural","5 - Iron"          ],
[  23,"Juab"                ,"Rural","0 - UDOT (Rural)"  ],
[  25,"Kane"                ,"Rural","0 - UDOT (Rural)"  ],
[  27,"Millard"             ,"Rural","0 - UDOT (Rural)"  ],
[  29,"Morgan"              ,"Rural","0 - UDOT (Rural)"  ],
[  31,"Piute"               ,"Rural","0 - UDOT (Rural)"  ],
[  33,"Rich"                ,"Rural","0 - UDOT (Rural)"  ],
[  35,"Salt Lake"           ,"Urban","1 - Wasatch Front" ],
[  37,"San Juan"            ,"Rural","0 - UDOT (Rural)"  ],
[  39,"Sanpete"             ,"Rural","0 - UDOT (Rural)"  ],
[  41,"Sevier"              ,"Rural","0 - UDOT (Rural)"  ],
[  43,"Summit"              ,"Rural","4 - Summit-Wasatch"],
[  45,"Tooele"              ,"Rural","0 - UDOT (Rural)"  ],
[  47,"Uintah"              ,"Rural","0 - UDOT (Rural)"  ],
[  49,"Utah"                ,"Urban","1 - Wasatch Front" ],
[  51,"Wasatch"             ,"Rural","4 - Summit-Wasatch"],
[  53,"Washington"          ,"Urban","3 - Dixie"         ],
[  55,"Wayne"               ,"Rural","0 - UDOT (Rural)"  ],
[  57,"Weber"               ,"Urban","1 - Wasatch Front" ],
[1049,"State of Utah"       ,"State","6 - State"         ],
[9003,"Box Elder - Rural"   ,"Rural","0 - UDOT (Rural)"  ],
[9103,"Box Elder - WFRC"    ,"Urban","1 - Wasatch Front" ],
[9057,"Weber - Ogden Valley","Rural","0 - UDOT (Rural)"  ],
[9157,"Weber - WFRC"        ,"Urban","1 - Wasatch Front" ]
],columns=["CO_FIPS_split","CO_NAME","Urban_Rural","Subarea"])

counties_more_df['CO_NAME'] = counties_more_df["CO_NAME"].str.upper()

counties_more_df

    CO_FIPS_split               CO_NAME Urban_Rural             Subarea
0               1                BEAVER       Rural    0 - UDOT (Rural)
1               3             BOX ELDER       Rural    0 - UDOT (Rural)
2               5                 CACHE       Urban           2 - Cache
3               7                CARBON       Rural    0 - UDOT (Rural)
4               9               DAGGETT       Rural    0 - UDOT (Rural)
5              11                 DAVIS       Urban   1 - Wasatch Front
6              13              DUCHESNE       Rural    0 - UDOT (Rural)
7              15                 EMERY       Rural    0 - UDOT (Rural)
8              17              GARFIELD       Rural    0 - UDOT (Rural)
9              19                 GRAND       Rural    0 - UDOT (Rural)
10             21                  IRON       Rural            5 - Iron
11             23                  JUAB       Rural    0 - UDOT (Rural)
12             25                  KANE       Rural    0 - UDOT (Rural)
13             27               MILLARD       Rural    0 - UDOT (Rural)
14             29                MORGAN       Rural    0 - UDOT (Rural)
15             31                 PIUTE       Rural    0 - UDOT (Rural)
16             33                  RICH       Rural    0 - UDOT (Rural)
17             35             SALT LAKE       Urban   1 - Wasatch Front
18             37              SAN JUAN       Rural    0 - UDOT (Rural)
19             39               SANPETE       Rural    0 - UDOT (Rural)
20             41                SEVIER       Rural    0 - UDOT (Rural)
21             43                SUMMIT       Rural  4 - Summit-Wasatch
22             45                TOOELE       Rural    0 - UDOT (Rural)
23             47                UINTAH       Rural    0 - UDOT (Rural)
24             49                  UTAH       Urban   1 - Wasatch Front
25             51               WASATCH       Rural  4 - Summit-Wasatch
26             53            WASHINGTON       Urban           3 - Dixie
27             55                 WAYNE       Rural    0 - UDOT (Rural)
28             57                 WEBER       Urban   1 - Wasatch Front
29           1049         STATE OF UTAH       State           6 - State
30           9003     BOX ELDER - RURAL       Rural    0 - UDOT (Rural)
31           9103      BOX ELDER - WFRC       Urban   1 - Wasatch Front
32           9057  WEBER - OGDEN VALLEY       Rural    0 - UDOT (Rural)
33           9157          WEBER - WFRC       Urban   1 - Wasatch Front

In [3]:
se_df = pd.concat([pd.read_csv('intermediate/split_emp_with_hbj.csv'), pd.read_csv('intermediate/split_pop.csv')]).drop(columns=['CO_FIPS'])
se_df

      CO_FIPS_split  YEAR VARIABLE   VALUE
0                 1  2023     AGRI     721
1                 1  2023     CONS     272
2                 1  2023     FOOD     509
3                 1  2023     GVED     780
4                 1  2023      HBJ     159
...             ...   ...      ...     ...
9928           9157  2065    HHPOP  367411
9929           9157  2065  POP0017   59084
9930           9157  2065  POP1864  222289
9931           9157  2065   POP65P   91658
9932           9157  2065   TOTPOP  373033

[26961 rows x 4 columns]

In [4]:
se_df[(se_df['YEAR']==2023) & (se_df['VARIABLE']=='HH')]

      CO_FIPS_split  YEAR VARIABLE   VALUE
1                 1  2023       HH    2381
302               3  2023       HH   20602
603               5  2023       HH   45994
904               7  2023       HH    7948
1205              9  2023       HH     420
1506             11  2023       HH  122330
1807             13  2023       HH    6777
2108             15  2023       HH    3794
2409             17  2023       HH    1963
2710             19  2023       HH    4170
3011             21  2023       HH   22269
3312             23  2023       HH    4093
3613             25  2023       HH    3208
3914             27  2023       HH    4476
4215             29  2023       HH    4333
4516             31  2023       HH     611
4817             33  2023       HH     985
5118             35  2023       HH  437303
5419             37  2023       HH    5396
5720             39  2023       HH    9246
6021             41  2023       HH    7598
6322             43  2023       HH   15294
6623             45  2023       HH   25795
6924             47  2023       HH   12505
7225             49  2023       HH  220334
7526             51  2023       HH   13205
7827             53  2023       HH   73168
8128             55  2023       HH     955
8429             57  2023       HH   97325
8730           9003  2023       HH    9456
9031           9057  2023       HH    3309
9332           9103  2023       HH   11146
9633           9157  2023       HH   94016

In [5]:
se_pivot_df = se_df.pivot(index=['CO_FIPS_split','YEAR'],columns='VARIABLE',values='VALUE').reset_index().fillna(0).astype(int)
se_pivot_df

VARIABLE,CO_FIPS_split,YEAR,AGRI,CONS,FOOD,GQPOP,GVED,HBJ,HH,HHPOP,...,MANU,MING,OFFI,OTHR,POP0017,POP1864,POP65P,RETL,TOTPOP,WSLE
0,1,2023,721,272,509,300,780,159,2381,7014,...,217,102,135,881,2019,4185,1110,528,7314,268
1,1,2024,739,302,481,291,801,0,2410,7048,...,233,152,147,1057,1997,4210,1132,497,7339,295
2,1,2025,736,388,483,369,820,0,2472,7163,...,237,180,149,1060,2071,4310,1152,506,7533,299
3,1,2026,736,393,496,351,915,0,2516,7226,...,240,215,149,1082,2030,4353,1194,540,7577,324
4,1,2027,733,343,497,295,959,0,2561,7287,...,242,247,148,1077,1996,4363,1223,542,7582,324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,9157,2061,1324,17426,9917,5406,33528,0,157287,356144,...,27747,166,13890,53540,59730,216417,85404,20003,361551,11290
1415,9157,2062,1317,17505,9912,5460,33686,0,159127,358961,...,27888,166,13972,53808,59495,217801,87125,20088,364421,11313
1416,9157,2063,1310,17576,9907,5513,33838,0,160960,361776,...,28035,165,14050,54081,59303,219248,88737,20174,367288,11336
1417,9157,2064,1304,17642,9900,5567,33991,0,162781,364591,...,28183,165,14127,54362,59165,220852,90141,20264,370158,11358
1418,9157,2065,1297,17705,9894,5622,34143,0,164591,367411,...,28335,164,14202,54646,59084,222289,91658,20356,373033,11381

In [6]:
# identify numeric columns except keys
value_cols = [c for c in se_pivot_df.columns if c not in ["CO_FIPS_split", "YEAR"]]

# --- filter only CO_FIPS < 100 before summing --- to avoid split records
se_utah_counties_df = se_pivot_df[se_pivot_df["CO_FIPS_split"] < 100].copy()

# compute statewide totals by YEAR using only CO_FIPS_split < 100
utah_totals_df = (
    se_utah_counties_df
        .groupby("YEAR")[value_cols]
        .sum()
        .reset_index()
)

# assign the statewide FIPS
utah_totals_df["CO_FIPS_split"] = 1049

# reorder columns
utah_totals_df = utah_totals_df[["CO_FIPS_split", "YEAR"] + value_cols]
utah_totals_df

VARIABLE,CO_FIPS_split,YEAR,AGRI,CONS,FOOD,GQPOP,GVED,HBJ,HH,HHPOP,...,MANU,MING,OFFI,OTHR,POP0017,POP1864,POP65P,RETL,TOTPOP,WSLE
0,1049,2023,25522,167128,151427,56647,354928,73641,1174478,3399800,...,159274,14788,273531,599770,899259,2133043,424145,229436,3456447,177500
1,1049,2024,26039,175205,155290,57530,375383,0,1201755,3449310,...,162381,15523,286767,633225,890489,2175807,440544,231878,3506840,184502
2,1049,2025,25949,180713,155637,58695,382552,0,1230457,3497694,...,165098,15371,291212,644717,912478,2191079,452838,234293,3556391,188324
3,1049,2026,25953,184824,156634,60108,385169,0,1259651,3544906,...,165987,15875,289775,652606,898954,2234608,471448,234038,3605012,189717
4,1049,2027,25848,191849,157000,61537,389375,0,1289257,3592066,...,167055,16227,289341,661115,887047,2276832,489724,236583,3653603,191793
5,1049,2028,25686,195868,156880,61833,392487,0,1318888,3638886,...,167960,15582,290575,669974,876667,2316979,507064,237580,3700715,192089
6,1049,2029,25543,200557,156181,61582,395567,0,1348197,3684994,...,169983,14762,293805,680659,868734,2354605,523235,239037,3746574,192673
7,1049,2030,25405,202746,155206,61154,398164,0,1376961,3730335,...,172758,14478,298080,690342,862599,2390799,538098,242426,3791492,192894
8,1049,2031,25288,203756,153445,61523,398367,0,1405063,3774853,...,175441,14536,301215,698474,856990,2427523,551866,246166,3836376,193199
9,1049,2032,25182,206124,152250,61939,399182,0,1432438,3818653,...,177940,15199,304868,709359,852534,2462494,565573,249225,3880591,193440
10,1049,2033,25207,207872,152108,62336,400121,0,1459080,3861957,...,180049,15860,310080,721076,849402,2495645,579244,251975,3924295,193286
11,1049,2034,25227,211976,156701,62678,402119,0,1485017,3904898,...,182231,16430,316048,738752,848187,2525437,593955,254716,3967570,193376
12,1049,2035,25198,214597,151572,62905,402150,0,1510407,3947818,...,183943,16632,321131,732152,849710,2550971,610042,254669,4010719,190838
13,1049,2036,25187,215154,152412,63124,403612,0,1535633,3991355,...,186871,16491,327622,740585,853492,2573478,627510,256242,4054478,189504
14,1049,2037,25186,217130,153680,63405,405955,0,1561239,4036976,...,189871,16327,332870,750845,858762,2597571,644043,258921,4100383,188825
15,1049,2038,25173,217039,154443,63866,409059,0,1587458,4085059,...,192614,16266,338862,764828,864692,2624018,660220,261531,4148922,189042
16,1049,2039,25161,217208,155369,64393,412939,0,1614117,4135036,...,195190,16226,344179,777783,872243,2649847,677337,264465,4199429,189271
17,1049,2040,25143,217022,156189,64897,417452,0,1640766,4185734,...,197613,16204,350059,790142,879721,2674627,696284,267306,4250631,189564
18,1049,2041,25121,216503,157237,65423,421054,0,1667184,4236398,...,199860,16249,355171,801600,888225,2696950,716652,270413,4301819,190009
19,1049,2042,25089,215898,157966,65956,425169,0,1693366,4286963,...,201965,16381,361177,812841,896793,2716252,739873,273054,4352916,190640
20,1049,2043,25055,215607,158944,66428,429804,0,1719470,4337874,...,203748,16490,366895,824073,907062,2732790,764443,275981,4404303,191276
21,1049,2044,25017,215540,159771,66899,434675,0,1745719,4389546,...,205542,16455,372901,835515,917872,2748701,789865,278822,4456445,192004
22,1049,2045,24985,216685,160736,67478,439952,0,1772333,4442439,...,207730,16407,379027,846479,928694,2764743,816479,282069,4509918,192720
23,1049,2046,24953,219287,161489,68264,445463,0,1799492,4496739,...,209946,16403,385855,856533,939029,2782941,843036,285149,4565001,193432
24,1049,2047,24920,223018,162268,69145,451059,0,1827331,4552454,...,212120,16509,393652,865866,948386,2803426,869788,288509,4621600,194083
25,1049,2048,24883,227739,163230,70164,456830,0,1855669,4609112,...,214359,16686,401726,874365,956412,2826949,895920,291852,4679278,194706
26,1049,2049,24843,233320,164234,71300,462611,0,1884333,4666025,...,216685,16874,409755,882737,962753,2854489,920074,295244,4737324,195281
27,1049,2050,24796,239384,165352,72524,469113,0,1913066,4722263,...,219038,17056,417766,891695,967120,2884290,943377,298892,4794788,195947
28,1049,2051,24752,245556,166224,73798,474192,0,1941599,4777119,...,221481,17216,423642,899207,969461,2916367,965087,302196,4850917,196338
29,1049,2052,24700,251832,167144,75056,479986,0,1969857,4830363,...,223760,17393,428853,906902,969967,2949895,985552,305578,4905419,196845
30,1049,2053,24643,258312,168113,76266,485873,0,1997949,4882273,...,225737,17595,433196,915222,969065,2983007,1006470,308943,4958540,197516
31,1049,2054,24593,265066,169006,77391,491799,0,2025993,4933209,...,227587,17737,437532,923223,967375,3014780,1028451,312319,5010597,198140
32,1049,2055,24518,272152,169937,78425,497701,0,2054082,4983380,...,229271,17825,441595,931505,965121,3044774,1051913,315708,5061802,198928
33,1049,2056,24461,277423,170675,79409,503947,0,2082123,5032743,...,230710,17747,445633,940598,962569,3072668,1076922,318515,5112155,199961
34,1049,2057,24397,281471,171194,80343,509274,0,2110026,5081290,...,232298,17468,449908,948889,959963,3099491,1102181,320986,5161637,200773
35,1049,2058,24329,284822,171716,81200,514329,0,2137878,5129277,...,233960,17208,454322,956881,957510,3126088,1126884,323424,5210479,201573
36,1049,2059,24256,287755,172230,82008,519121,0,2165766,5177101,...,235634,17038,458775,964720,955460,3153479,1150172,325858,5259109,202373
37,1049,2060,24180,290398,172752,82784,524281,0,2193770,5224962,...,237311,16953,463228,972475,953953,3179611,1174180,328259,5307747,203176
38,1049,2061,24127,292811,173329,83532,527992,0,2221786,5272840,...,238981,16905,467429,980213,953146,3203803,1199427,330716,5356372,203841
39,1049,2062,24067,295121,173929,84252,532422,0,2249736,5320694,...,240678,16872,471469,987997,953114,3224579,1227248,333244,5404943,204516
40,1049,2063,24009,297356,174541,84946,536871,0,2277561,5368530,...,242386,16840,475368,995773,953914,3245156,1254407,335830,5453475,205209
41,1049,2064,23951,299498,175166,85665,541353,0,2305212,5416327,...,244091,16810,479157,1003507,955581,3267062,1279346,338458,5501990,205901
42,1049,2065,23895,301563,175808,86434,545867,0,2332663,5464090,...,245804,16784,482855,1011212,958119,3285334,1307065,341127,5550524,206592

In [7]:
se_final_df = pd.concat([se_pivot_df,utah_totals_df]).copy()

# adj for rounding issues
se_final_df['POP65P'] = se_final_df['TOTPOP'] - se_final_df['POP0017'] - se_final_df['POP1864']
se_final_df['GQPOP'] = se_final_df['TOTPOP'] - se_final_df['HHPOP']

se_final_df[';INDEX'] = se_final_df['CO_FIPS_split'].astype(str) + se_final_df['YEAR'].astype(str)
se_final_df[';INDEX'] = se_final_df[';INDEX'].astype(int)

se_final_df['HHSIZE'] = se_final_df['HHPOP'] / se_final_df['HH']
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].replace([np.inf, -np.inf], 0)
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].fillna(0).round(2)

se_final_df['ALLEMP'] = se_final_df['RETL'] + se_final_df['FOOD'] + se_final_df['MANU'] + se_final_df['WSLE'] + se_final_df['OFFI'] + se_final_df['GVED'] + se_final_df['HLTH'] + se_final_df['OTHR'] + se_final_df['AGRI'] + se_final_df['MING'] + se_final_df['CONS'] + se_final_df['HBJ']

se_final_df = se_final_df[[';INDEX','CO_FIPS_split','YEAR','TOTPOP','GQPOP','HHPOP','HH','HHSIZE','POP0017','POP1864','POP65P','ALLEMP','RETL','FOOD','MANU','WSLE','OFFI','GVED','HLTH','OTHR','AGRI','MING','CONS','HBJ']]

# add extra columns
se_final_df['Job_HH'] = np.round(se_final_df['ALLEMP'] / se_final_df['HH'],2)
se_final_df['WrkPop_Job'] = np.round(se_final_df['POP1864'] / se_final_df['ALLEMP'],2)

se_final_df = se_final_df.merge(counties_more_df, on='CO_FIPS_split').sort_values([';INDEX'])

se_final_df

,;INDEX,CO_FIPS_split,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea
0,12023,1,2023,7314,300,7014,2381,2.95,2019,4185,...,881,721,102,272,159,1.99,0.89,BEAVER,Rural,0 - UDOT (Rural)
1,12024,1,2024,7339,291,7048,2410,2.92,1997,4210,...,1057,739,152,302,0,2.02,0.86,BEAVER,Rural,0 - UDOT (Rural)
2,12025,1,2025,7533,370,7163,2472,2.90,2071,4310,...,1060,736,180,388,0,2.04,0.86,BEAVER,Rural,0 - UDOT (Rural)
3,12026,1,2026,7577,351,7226,2516,2.87,2030,4353,...,1082,736,215,393,0,2.10,0.83,BEAVER,Rural,0 - UDOT (Rural)
4,12027,1,2027,7582,295,7287,2561,2.85,1996,4363,...,1077,733,247,343,0,2.07,0.82,BEAVER,Rural,0 - UDOT (Rural)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,91572061,9157,2061,361551,5407,356144,157287,2.26,59730,216417,...,53540,1324,166,17426,0,1.36,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1415,91572062,9157,2062,364421,5460,358961,159127,2.26,59495,217801,...,53808,1317,166,17505,0,1.36,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1416,91572063,9157,2063,367288,5512,361776,160960,2.25,59303,219248,...,54081,1310,165,17576,0,1.35,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1417,91572064,9157,2064,370158,5567,364591,162781,2.24,59165,220852,...,54362,1304,165,17642,0,1.34,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1418,91572065,9157,2065,373033,5622,367411,164591,2.23,59084,222289,...,54646,1297,164,17705,0,1.33,1.02,WEBER - WFRC,Urban,1 - Wasatch Front

# Export final table

In [8]:
# Final columns
# ;Index,CO_FIPS,YEAR,TOTPOP,GQ_Pop,HH_Pop,HH,HH_Size,POP_00_17,POP_18_64,POP_65P,ALLEMP,RETL,FOOD,MANU,WSLE,OFFI,GVED,HLTH,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea

# EXPORT ONLY 2023 - FOR NOW
se_final_df.to_csv('results/ControlTotal_SE_AllCounties.csv', index=False)
se_final_df

,;INDEX,CO_FIPS_split,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea
0,12023,1,2023,7314,300,7014,2381,2.95,2019,4185,...,881,721,102,272,159,1.99,0.89,BEAVER,Rural,0 - UDOT (Rural)
1,12024,1,2024,7339,291,7048,2410,2.92,1997,4210,...,1057,739,152,302,0,2.02,0.86,BEAVER,Rural,0 - UDOT (Rural)
2,12025,1,2025,7533,370,7163,2472,2.90,2071,4310,...,1060,736,180,388,0,2.04,0.86,BEAVER,Rural,0 - UDOT (Rural)
3,12026,1,2026,7577,351,7226,2516,2.87,2030,4353,...,1082,736,215,393,0,2.10,0.83,BEAVER,Rural,0 - UDOT (Rural)
4,12027,1,2027,7582,295,7287,2561,2.85,1996,4363,...,1077,733,247,343,0,2.07,0.82,BEAVER,Rural,0 - UDOT (Rural)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,91572061,9157,2061,361551,5407,356144,157287,2.26,59730,216417,...,53540,1324,166,17426,0,1.36,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1415,91572062,9157,2062,364421,5460,358961,159127,2.26,59495,217801,...,53808,1317,166,17505,0,1.36,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1416,91572063,9157,2063,367288,5512,361776,160960,2.25,59303,219248,...,54081,1310,165,17576,0,1.35,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1417,91572064,9157,2064,370158,5567,364591,162781,2.24,59165,220852,...,54362,1304,165,17642,0,1.34,1.01,WEBER - WFRC,Urban,1 - Wasatch Front
1418,91572065,9157,2065,373033,5622,367411,164591,2.23,59084,222289,...,54646,1297,164,17705,0,1.33,1.02,WEBER - WFRC,Urban,1 - Wasatch Front